#pragma once
#include "NativeGameplayTags.h"

namespace KausGameplayTags
{
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Interaction_Activate);

	//Message - UI
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Event_Dialogue_Closed);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Event_Dialogue_ForceClose);

	//UI
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Layer_Game);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Layer_GameOnMenu);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Layer_Menu);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Layer_Modal);

	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Group_Intro);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Group_MainMenu);

	//Input - Native
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);

	//InputTag - Camera
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Camera_ZZZ_Move);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Camera_ZZZ_Zoom);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Camera_ZZZ_Look);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Camera_ZZZ_RotateSnap);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Camera_ZZZ_Reset);

	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Camera_ThirdPerson_Look);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Camera_Switch_TPAndZZZ);

	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Orbit_Toggle);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MouseClick);

	//Input - UI
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Interaction_Event_SelectionChanged);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UI_Interaction_MultipleTarget_Wheel);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UI_Interaction_MultipleTarget_Up);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UI_Interaction_MultipleTarget_Down);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Event_Interaction_CycleNext); 
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Event_Interaction_CyclePrev); 


	//Movement
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Gameplay_MovementStopped);

	//Interaction
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_INTERACTION_DURATION_MESSAGE);

	//Hardware
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Platform_Trait_Input_HardwareCursor);

	//Ability System - Message
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ABILITY_SIMPLE_FAILURE_MESSAGE);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ABILITY_PLAY_MONTAGE_FAILURE_MESSAGE);
	
	//Unit status state
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Unit_Status_Death);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Unit_Status_Death_Dying);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Unit_Status_Death_Dead);

	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_IsDead);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cooldown);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cost);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsBlocked);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsMissing);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Networking);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_ActivationGroup);

	//Camera
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Camera_Mode_FirstPerson);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Camera_Mode_ThirdPerson);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Camera_Mode_ZZZ);

	
	//MainScreen - InteractionSet
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_MainScreen_InteractionSet_1); //Character가 숨어 있는 상호작용 셋
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_MainScreen_InteractionSet_2); //Character를 사선으로 비추는 상호작용 셋
	
	//Demo
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Demo_Choise);
}
