#pragma once
#include "NativeGameplayTags.h"

namespace KausUnitTags
{
	//Identity
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Identity_Unit_SimpleBot);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Identity_Unit_Iris);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Identity_Unit_Flare);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Identity_Unit_Sachi);
	
	//State
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_State_Stand);	

	//Stats
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Vitality);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_ReactionSpeed);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Logic);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_SelfEsteem);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Motivation);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Depression);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Anxiety);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Anger);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Dialogue_StatModify);
	
	//Emotion
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Emotion_Neutral);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Emotion_Happy);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Emotion_Sad);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Emotion_Angry);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Emotion_Anxious);
	KAUS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Emotion_Comment);
	
}