;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Identity.Item.Monitor",DevComment="")
+GameplayTagList=(Tag="Identity.Item.Phone",DevComment="")
+GameplayTagList=(Tag="Identity.Unit.Narrative",DevComment="")
+GameplayTagList=(Tag="Identity.Unit.Tofu",DevComment="")
+GameplayTagList=(Tag="Kaus.Event.Dialogue.Demo.Count",DevComment="")

