;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Event.Seq",DevComment="")
+GameplayTagList=(Tag="Identity.Item.Bed",DevComment="")
+GameplayTagList=(Tag="Identity.Item.Door",DevComment="")
+GameplayTagList=(Tag="Identity.Item.Monitor",DevComment="")
+GameplayTagList=(Tag="Identity.Item.Phone",DevComment="")
+GameplayTagList=(Tag="Identity.Unit.Narrative",DevComment="")
+GameplayTagList=(Tag="Identity.Unit.Tofu",DevComment="")
+GameplayTagList=(Tag="Kaus.Event.Dialogue.Demo.Count",DevComment="")
+GameplayTagList=(Tag="Node",DevComment="")
+GameplayTagList=(Tag="Node.State.Disable",DevComment="")
+GameplayTagList=(Tag="Node.State.Enable.Mutiple",DevComment="")
+GameplayTagList=(Tag="Node.State.Enable.One",DevComment="")
+GameplayTagList=(Tag="Phase.Story.Day01.Day.Main.Disable",DevComment="")
+GameplayTagList=(Tag="Phase.Story.Day01.Day.Main.Enable",DevComment="")
+GameplayTagList=(Tag="Phase.Story.Day01.Day.Sub01",DevComment="")
+GameplayTagList=(Tag="Phase.Story.Day01.Day.Sub.Disable",DevComment="")
+GameplayTagList=(Tag="Phase.Story.Day01.Day.Sub.Enable",DevComment="")
+GameplayTagList=(Tag="Phase.Story.Day01.Night",DevComment="")
+GameplayTagList=(Tag="UI.Event.Dialogue.Tutorial.Addon",DevComment="")
+GameplayTagList=(Tag="UI.Event.Dialogue.Tutorial.Addon.Off",DevComment="")
+GameplayTagList=(Tag="UI.Event.Dialogue.Tutorial.Addon.On",DevComment="")
+GameplayTagList=(Tag="UI.Event.Dialogue.Tutorial.TimerGlow",DevComment="")
+GameplayTagList=(Tag="UI.Event.Dialogue.Tutorial.TimerGlow.Off",DevComment="")
+GameplayTagList=(Tag="UI.Event.Dialogue.Tutorial.TimerGlow.On",DevComment="")
+GameplayTagList=(Tag="UI.Layer.Modal.Tutorial",DevComment="")

